apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  DB_PASS: ZXhhbXBsZQ==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DB: endgame
  DB_USER: john
  DB_HOST: postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: s6confidence/thunder-backend:v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef: 
                name: api-secret 
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP      
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always 

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  type: ClusterIP
  selector:
    app: api

