apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXM=
  REDIS_MASTER_PASSWORD: cmVkaXM=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  HOSTNAME: redis-master
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: s6confidence/thunder-frontend:v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef: 
                  name: frontend-secret          
            - configMapRef:
                  name: frontend-config
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP    
          resources:      
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always 

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  type: NodePort
  selector:
    app: frontend
